const stdLatexCommandsMacros = {
  Alpha: {
    args: 0,
    captureSelection: true,
    def: "\\mathrm{A}",
    expand: true,
  },
  Approxcolon: {
    args: 0,
    captureSelection: true,
    def: "\\mathrel{\\approx\\mathrel{\\mkern-1.2mu}\\dblcolon}",
    expand: true,
  },
  Beta: { args: 0, captureSelection: true, def: "\\mathrm{B}", expand: true },
  Bra: {
    args: 1,
    captureSelection: false,
    def: "\\left\\langle #1\\right|",
    expand: true,
  },
  Braket: {
    args: 1,
    captureSelection: false,
    def: "\\left\\langle{#1}\\right\\rangle",
    expand: true,
  },
  Chi: { args: 0, captureSelection: true, def: "\\mathrm{X}", expand: true },
  Colonapprox: {
    args: 0,
    captureSelection: true,
    def: '{\\mathop{\\char"2237\\char"2248}}',
    expand: false,
  },
  Colondash: {
    args: 0,
    captureSelection: true,
    def: "\\mathrel{\\dblcolon\\mathrel{\\mkern-1.2mu}\\mathrel{-}}",
    expand: false,
  },
  Coloneq: {
    args: 0,
    captureSelection: true,
    def: '{\\mathop{\\char"2237\\char"2212}}',
    expand: false,
  },
  Coloneqq: {
    args: 0,
    captureSelection: true,
    def: '{\\mathop{\\char"2237\\char"3D}}',
    expand: false,
  },
  Colonsim: {
    args: 0,
    captureSelection: true,
    def: '{\\mathop{\\char"2237\\char"223C}}',
    expand: false,
  },
  Complex: {
    args: 0,
    captureSelection: true,
    def: "\\mathbb{C}",
    expand: true,
  },
  Dagger: { args: 0, captureSelection: true, def: "\\ddagger", expand: true },
  Darr: { args: 0, captureSelection: true, def: "\\Downarrow", expand: true },
  Dashcolon: {
    args: 0,
    captureSelection: true,
    def: "\\mathrel{\\mathrel{-}\\mathrel{\\mkern-1.2mu}\\dblcolon}",
    expand: false,
  },
  Epsilon: {
    args: 0,
    captureSelection: true,
    def: "\\mathrm{E}",
    expand: true,
  },
  Eqcolon: {
    args: 0,
    captureSelection: true,
    def: '{\\mathop{\\char"2212\\char"2237}}',
    expand: false,
  },
  Eqqcolon: {
    args: 0,
    captureSelection: true,
    def: '{\\mathop{\\char"3D\\char"2237}}',
    expand: false,
  },
  Eta: { args: 0, captureSelection: true, def: "\\mathrm{H}", expand: true },
  Harr: {
    args: 0,
    captureSelection: true,
    def: "\\Leftrightarrow",
    expand: true,
  },
  Iota: { args: 0, captureSelection: true, def: "\\mathrm{I}", expand: true },
  Kappa: { args: 0, captureSelection: true, def: "\\mathrm{K}", expand: true },
  Ket: {
    args: 1,
    captureSelection: false,
    def: "\\left|#1\\right\\rangle",
    expand: true,
  },
  Larr: { args: 0, captureSelection: true, def: "\\Leftarrow", expand: true },
  Lrarr: {
    args: 0,
    captureSelection: true,
    def: "\\Leftrightarrow",
    expand: true,
  },
  Mu: { args: 0, captureSelection: true, def: "\\mathrm{M}", expand: true },
  N: { args: 0, captureSelection: true, def: "\\mathbb{N}", expand: true },
  Nu: { args: 0, captureSelection: true, def: "\\mathrm{N}", expand: true },
  Omicron: {
    args: 0,
    captureSelection: true,
    def: "\\mathrm{O}",
    expand: true,
  },
  R: { args: 0, captureSelection: true, def: "\\mathbb{R}", expand: true },
  Rarr: { args: 0, captureSelection: true, def: "\\Rightarrow", expand: true },
  Reals: { args: 0, captureSelection: true, def: "\\mathbb{R}", expand: true },
  Rho: { args: 0, captureSelection: true, def: "\\mathrm{P}", expand: true },
  Set: {
    args: 1,
    captureSelection: false,
    def: "\\left\\lbrace #1 \\right\\rbrace",
    expand: true,
  },
  Simcolon: {
    args: 0,
    captureSelection: true,
    def: "\\mathrel{\\sim\\mathrel{\\mkern-1.2mu}\\dblcolon}",
    expand: true,
  },
  Tau: { args: 0, captureSelection: true, def: "\\mathrm{T}", expand: true },
  Uarr: { args: 0, captureSelection: true, def: "\\Uparrow", expand: true },
  Z: { args: 0, captureSelection: true, def: "\\mathbb{Z}", expand: true },
  Zeta: { args: 0, captureSelection: true, def: "\\mathrm{Z}", expand: true },
  alef: { args: 0, captureSelection: true, def: "\\aleph", expand: true },
  alefsym: { args: 0, captureSelection: true, def: "\\aleph", expand: true },
  angl: {
    args: 1,
    captureSelection: true,
    def: "\\enclose{actuarial}{#1}",
    expand: true,
  },
  anglk: {
    args: 0,
    captureSelection: true,
    def: "\\enclose{actuarial}{k}",
    expand: true,
  },
  angln: {
    args: 0,
    captureSelection: true,
    def: "\\enclose{actuarial}{n}",
    expand: true,
  },
  anglr: {
    args: 0,
    captureSelection: true,
    def: "\\enclose{actuarial}{r}",
    expand: true,
  },
  approxcolon: {
    args: 0,
    captureSelection: true,
    def: "\\mathrel{\\approx\\mathrel{\\mkern-1.2mu}\\vcentcolon}",
    expand: true,
  },
  approxcoloncolon: {
    args: 0,
    captureSelection: true,
    def: "\\mathrel{\\approx\\mathrel{\\mkern-1.2mu}\\dblcolon}",
    expand: true,
  },
  argmax: {
    args: 0,
    captureSelection: true,
    def: "\\operatorname*{arg\\,max}",
    expand: true,
  },
  argmin: {
    args: 0,
    captureSelection: true,
    def: "\\operatorname*{arg\\,min}",
    expand: true,
  },
  bmod: {
    args: 0,
    captureSelection: true,
    def: "\\;\\mathbin{\\operatorname{mod }}",
    expand: false,
  },
  bra: {
    args: 1,
    captureSelection: false,
    def: "\\mathinner{\\langle{#1}|}",
    expand: true,
  },
  braket: {
    args: 1,
    captureSelection: false,
    def: "\\mathinner{\\langle{#1}\\rangle}",
    expand: true,
  },
  bull: { args: 0, captureSelection: true, def: "\\bullet", expand: true },
  capitalDifferentialD: {
    args: 0,
    captureSelection: true,
    def: "\\mathrm{D}",
    expand: true,
  },
  clubs: { args: 0, captureSelection: true, def: "\\clubsuit", expand: true },
  cnums: { args: 0, captureSelection: true, def: "\\mathbb{C}", expand: true },
  colonapprox: {
    args: 0,
    captureSelection: true,
    def: '{\\mathop{\\char"003A\\char"2248}}',
    expand: false,
  },
  coloncolon: {
    args: 0,
    captureSelection: true,
    def: "\\dblcolon",
    expand: true,
  },
  coloncolonapprox: {
    args: 0,
    captureSelection: true,
    def: "\\Colonapprox",
    expand: true,
  },
  coloncolonequals: {
    args: 0,
    captureSelection: true,
    def: "\\Coloneq",
    expand: true,
  },
  coloncolonminus: {
    args: 0,
    captureSelection: true,
    def: "\\Colondash",
    expand: true,
  },
  coloncolonsim: {
    args: 0,
    captureSelection: true,
    def: "\\Colonsim",
    expand: true,
  },
  colondash: {
    args: 0,
    captureSelection: true,
    def: "\\mathrel{\\vcentcolon\\mathrel{\\mkern-1.2mu}\\mathrel{-}}",
    expand: false,
  },
  coloneq: {
    args: 0,
    captureSelection: true,
    def: '{\\mathop{\\char"3A\\char"2212}}',
    expand: false,
  },
  coloneqq: {
    args: 0,
    captureSelection: true,
    def: '{\\mathop{\\char"2254}}',
    expand: false,
  },
  colonequals: {
    args: 0,
    captureSelection: true,
    def: "\\coloneq",
    expand: true,
  },
  colonminus: {
    args: 0,
    captureSelection: true,
    def: "\\colondash",
    expand: true,
  },
  colonsim: {
    args: 0,
    captureSelection: true,
    def: '{\\mathop{\\char"3A\\char"223C}}',
    expand: false,
  },
  dArr: { args: 0, captureSelection: true, def: "\\Downarrow", expand: true },
  darr: { args: 0, captureSelection: true, def: "\\downarrow", expand: true },
  dashcolon: {
    args: 0,
    captureSelection: true,
    def: "\\mathrel{\\mathrel{-}\\mathrel{\\mkern-1.2mu}\\vcentcolon}",
    expand: false,
  },
  dblcolon: {
    args: 0,
    captureSelection: true,
    def: '{\\mathop{\\char"2237}}',
    expand: false,
  },
  diamonds: {
    args: 0,
    captureSelection: true,
    def: "\\diamondsuit",
    expand: true,
  },
  differentialD: {
    args: 0,
    captureSelection: true,
    def: "\\mathrm{d}",
    expand: true,
  },
  doubleStruckCapitalN: {
    args: 0,
    captureSelection: true,
    def: "\\mathbb{N}",
    expand: true,
  },
  doubleStruckCapitalP: {
    args: 0,
    captureSelection: true,
    def: "\\mathbb{P}",
    expand: true,
  },
  doubleStruckCapitalQ: {
    args: 0,
    captureSelection: true,
    def: "\\mathbb{Q}",
    expand: true,
  },
  doubleStruckCapitalR: {
    args: 0,
    captureSelection: true,
    def: "\\mathbb{R}",
    expand: true,
  },
  doubleStruckCapitalZ: {
    args: 0,
    captureSelection: true,
    def: "\\mathbb{Z}",
    expand: true,
  },
  empty: { args: 0, captureSelection: true, def: "\\emptyset", expand: true },
  eqcolon: {
    args: 0,
    captureSelection: true,
    def: '{\\mathop{\\char"2239}}',
    expand: false,
  },
  eqqcolon: {
    args: 0,
    captureSelection: true,
    def: '{\\mathop{\\char"2255}}',
    expand: false,
  },
  equalscolon: {
    args: 0,
    captureSelection: true,
    def: "\\eqcolon",
    expand: true,
  },
  equalscoloncolon: {
    args: 0,
    captureSelection: true,
    def: "\\Eqcolon",
    expand: true,
  },
  exist: { args: 0, captureSelection: true, def: "\\exists", expand: true },
  exponentialE: {
    args: 0,
    captureSelection: true,
    def: "\\mathrm{e}",
    expand: true,
  },
  gothicCapitalC: {
    args: 0,
    captureSelection: true,
    def: "\\mathfrak{C}",
    expand: true,
  },
  gothicCapitalH: {
    args: 0,
    captureSelection: true,
    def: "\\mathfrak{H}",
    expand: true,
  },
  gothicCapitalI: {
    args: 0,
    captureSelection: true,
    def: "\\mathfrak{I}",
    expand: true,
  },
  gothicCapitalR: {
    args: 0,
    captureSelection: true,
    def: "\\mathfrak{R}",
    expand: true,
  },
  hArr: {
    args: 0,
    captureSelection: true,
    def: "\\Leftrightarrow",
    expand: true,
  },
  harr: {
    args: 0,
    captureSelection: true,
    def: "\\leftrightarrow",
    expand: true,
  },
  hearts: { args: 0, captureSelection: true, def: "\\heartsuit", expand: true },
  iff: {
    args: 0,
    captureSelection: true,
    def: '\\;\\char"27FA\\;',
    expand: true,
    primitive: true,
  },
  image: { args: 0, captureSelection: true, def: "\\Im", expand: true },
  imaginaryI: {
    args: 0,
    captureSelection: true,
    def: "\\mathrm{i}",
    expand: true,
  },
  imaginaryJ: {
    args: 0,
    captureSelection: true,
    def: "\\mathrm{j}",
    expand: true,
  },
  infin: { args: 0, captureSelection: true, def: "\\infty", expand: true },
  injlim: {
    args: 0,
    captureSelection: true,
    def: "\\operatorname*{inj\\,lim}",
    expand: true,
  },
  isin: { args: 0, captureSelection: true, def: "\\in", expand: true },
  ket: {
    args: 1,
    captureSelection: false,
    def: "\\mathinner{|{#1}\\rangle}",
    expand: true,
  },
  lArr: { args: 0, captureSelection: true, def: "\\Leftarrow", expand: true },
  lang: { args: 0, captureSelection: true, def: "\\langle", expand: true },
  larr: { args: 0, captureSelection: true, def: "\\leftarrow", expand: true },
  liminf: {
    args: 0,
    captureSelection: true,
    def: "\\operatorname*{lim\\,inf}",
    expand: true,
  },
  limsup: {
    args: 0,
    captureSelection: true,
    def: "\\operatorname*{lim\\,sup}",
    expand: true,
  },
  lrArr: {
    args: 0,
    captureSelection: true,
    def: "\\Leftrightarrow",
    expand: true,
  },
  lrarr: {
    args: 0,
    captureSelection: true,
    def: "\\leftrightarrow",
    expand: true,
  },
  mathstrut: {
    args: 0,
    captureSelection: true,
    def: "\\vphantom{(}",
    expand: true,
    primitive: true,
  },
  minuscolon: {
    args: 0,
    captureSelection: true,
    def: "\\dashcolon",
    expand: true,
  },
  minuscoloncolon: {
    args: 0,
    captureSelection: true,
    def: "\\Dashcolon",
    expand: true,
  },
  mod: {
    args: 1,
    captureSelection: true,
    def: "\\quad\\operatorname{mod}\\,\\,#1",
    expand: false,
  },
  natnums: {
    args: 0,
    captureSelection: true,
    def: "\\mathbb{N}",
    expand: true,
  },
  nicefrac: {
    args: 2,
    captureSelection: true,
    def: "^{#1}\\!\\!/\\!_{#2}",
    expand: true,
  },
  notni: {
    args: 0,
    captureSelection: true,
    def: "\\mathrel{\\char`∌}",
    expand: true,
  },
  ordinarycolon: { args: 0, captureSelection: true, def: ":", expand: false },
  phase: {
    args: 1,
    captureSelection: false,
    def: "\\enclose{phasorangle}{#1}",
    expand: true,
  },
  plim: {
    args: 0,
    captureSelection: true,
    def: "\\mathop{\\operatorname{plim}}\\limits",
    expand: true,
  },
  plusmn: { args: 0, captureSelection: true, def: "\\pm", expand: true },
  pmod: {
    args: 1,
    captureSelection: false,
    def: "\\quad(\\operatorname{mod}\\ #1)",
    expand: false,
  },
  projlim: {
    args: 0,
    captureSelection: true,
    def: "\\operatorname*{proj\\,lim}",
    expand: true,
  },
  rArr: { args: 0, captureSelection: true, def: "\\Rightarrow", expand: true },
  rD: { args: 0, captureSelection: true, def: "\\mathrm{D}", expand: true },
  rang: { args: 0, captureSelection: true, def: "\\rangle", expand: true },
  rarr: { args: 0, captureSelection: true, def: "\\rightarrow", expand: true },
  ratio: { args: 0, captureSelection: true, def: "\\vcentcolon", expand: true },
  rd: { args: 0, captureSelection: true, def: "\\mathrm{d}", expand: true },
  real: { args: 0, captureSelection: true, def: "\\Re", expand: true },
  reals: { args: 0, captureSelection: true, def: "\\mathbb{R}", expand: true },
  scriptCapitalE: {
    args: 0,
    captureSelection: true,
    def: "\\mathscr{E}",
    expand: true,
  },
  scriptCapitalH: {
    args: 0,
    captureSelection: true,
    def: "\\mathscr{H}",
    expand: true,
  },
  scriptCapitalL: {
    args: 0,
    captureSelection: true,
    def: "\\mathscr{L}",
    expand: true,
  },
  sdot: { args: 0, captureSelection: true, def: "\\cdot", expand: true },
  sect: { args: 0, captureSelection: true, def: "\\S", expand: true },
  set: {
    args: 1,
    captureSelection: false,
    def: "\\mathinner{\\lbrace #1 \\rbrace}",
    expand: true,
  },
  simcolon: {
    args: 0,
    captureSelection: true,
    def: "\\mathrel{\\sim\\mathrel{\\mkern-1.2mu}\\vcentcolon}",
    expand: true,
  },
  simcoloncolon: {
    args: 0,
    captureSelection: true,
    def: "\\mathrel{\\sim\\mathrel{\\mkern-1.2mu}\\dblcolon}",
    expand: true,
  },
  spades: { args: 0, captureSelection: true, def: "\\spadesuit", expand: true },
  sub: { args: 0, captureSelection: true, def: "\\subset", expand: true },
  sube: { args: 0, captureSelection: true, def: "\\subseteq", expand: true },
  supe: { args: 0, captureSelection: true, def: "\\supseteq", expand: true },
  thetasym: {
    args: 0,
    captureSelection: true,
    def: "\\vartheta",
    expand: true,
  },
  tripledash: {
    args: 0,
    captureSelection: true,
    def: "\\vphantom{-}\\raise{4mu}{\\mkern1.5mu\\rule{2mu}{1.5mu}\\mkern{2.25mu}\\rule{2mu}{1.5mu}\\mkern{2.25mu}\\rule{2mu}{1.5mu}\\mkern{2mu}}",
    expand: true,
  },
  uArr: { args: 0, captureSelection: true, def: "\\Uparrow", expand: true },
  uarr: { args: 0, captureSelection: true, def: "\\uparrow", expand: true },
  varDelta: {
    args: 0,
    captureSelection: true,
    def: "\\mathit{\\Delta}",
    expand: false,
  },
  varGamma: {
    args: 0,
    captureSelection: true,
    def: "\\mathit{\\Gamma}",
    expand: false,
  },
  varLambda: {
    args: 0,
    captureSelection: true,
    def: "\\mathit{\\Lambda}",
    expand: false,
  },
  varOmega: {
    args: 0,
    captureSelection: true,
    def: "\\mathit{\\Omega}",
    expand: false,
  },
  varPhi: {
    args: 0,
    captureSelection: true,
    def: "\\mathit{\\Phi}",
    expand: false,
  },
  varPi: {
    args: 0,
    captureSelection: true,
    def: "\\mathit{\\Pi}",
    expand: false,
  },
  varPsi: {
    args: 0,
    captureSelection: true,
    def: "\\mathit{\\Psi}",
    expand: false,
  },
  varSigma: {
    args: 0,
    captureSelection: true,
    def: "\\mathit{\\Sigma}",
    expand: false,
  },
  varTheta: {
    args: 0,
    captureSelection: true,
    def: "\\mathit{\\Theta}",
    expand: false,
  },
  varUpsilon: {
    args: 0,
    captureSelection: true,
    def: "\\mathit{\\Upsilon}",
    expand: false,
  },
  varXi: {
    args: 0,
    captureSelection: true,
    def: "\\mathit{\\Xi}",
    expand: false,
  },
  varinjlim: {
    args: 0,
    captureSelection: true,
    def: "\\operatorname*{\\underrightarrow{lim}}",
    expand: true,
  },
  varliminf: {
    args: 0,
    captureSelection: true,
    def: "\\operatorname*{\\underline{lim}}",
    expand: true,
  },
  varlimsup: {
    args: 0,
    captureSelection: true,
    def: "\\operatorname*{\\overline{lim}}",
    expand: true,
  },
  varprojlim: {
    args: 0,
    captureSelection: true,
    def: "\\operatorname*{\\underleftarrow{lim}}",
    expand: true,
  },
  vcentcolon: {
    args: 0,
    captureSelection: true,
    def: "\\mathrel{\\mathop\\ordinarycolon}",
    expand: false,
  },
  weierp: { args: 0, captureSelection: true, def: "\\wp", expand: true },
};
