module DatasetPage exposing (..) -- former ingle page Main.elm
-- TO BUILD
-- remove /build folder
-- > make all
-- TO RUN
-- > elm-watch hot
-- NB: to change the executed js comment/uncomment in the index.html
-- ./dist/ui.js is generated by Makefile, from console: make all (after deleting /build folder)
-- app.js is generated by elm make src/Main.elm --output=app.js
-- elm-watch hot works with both (I assume it goes after index.html in the running folder)
import Platform.Cmd as Cmd
import Platform.Sub as Sub
import Task
import Debug exposing (log)
-- spreadsheetUI and pivot tables
-- import PersonValuePivot exposing (..)
import SpreadsheetUI exposing (..)

-- Drag and drop
import DnDTray exposing (..)
-- Dropdown
import Dropdown exposing (Msg(..), State, update)

-- XModel and CalcEngine
import CalcEngine exposing (Msg(..), update, viewConsole)
import TypesXModel exposing (XModel )
import XModel 
import TypesXModel exposing (..)
import XView
import Types exposing (CallTree(..), Error(..), Value(..), Env, Eval)

-- elm-interpreter
import Ports
import XModelHelpers
import FormulaParser

-- UI
import Browser

import Html exposing (Html)
import Html.Attributes as HtmlAttr exposing (style)
import Html.Events exposing (preventDefaultOn)
import Element exposing (..)
import Element.Font as UiFont
import Element.Background as Background
import MyColors exposing (..)

import Array
import Array2D
import Html exposing (a)
import FastDict as Dict exposing (Dict)
import Json.Encode
import Json.Decode as Decode
import Maybe.Extra exposing (prev)
import AppUtil





type alias Model =
    { spreadsheetUIModel : SpreadsheetUI.Model
    --, pivotModel : PersonValuePivot.Model
    , dndTrayModel : DnDTray.Model
    , calcModel : CalcEngine.Model
    , autoRecalc : Bool 
    , hints : List String 
    , editorInitialized : Bool
    }

initialModel : Result Error Env -> DatasetRef -> Model
initialModel env datasetRef =
    let
        initialCalcModel = CalcEngine.initialModel env datasetRef
        initialXModel = CalcEngine.getXModelFromEnv env |> Maybe.withDefault XModel.emptyXModel
        initialSpreadsheetUIModel = SpreadsheetUI.initialModel initialXModel datasetRef
        initialDnDTrayModel = DnDTray.initialModel
        -- initialTrayData = PersonValue.defaultTrayData
        initialTrayData = XView.defaultTrayData initialXModel.dims
                initialSpreadsheetUIModel.curDataset initialSpreadsheetUIModel.curDatasetView
    in

    -- imported components
    { spreadsheetUIModel = initialSpreadsheetUIModel
    , dndTrayModel = { initialDnDTrayModel | trayData = initialTrayData }
    , calcModel = initialCalcModel
    , autoRecalc = False
    , hints = []
    , editorInitialized = False
    }

type Msg 
    = DnDTrayMsg DnDTray.Msg
    | SpreadsheetUIMsg SpreadsheetUI.Msg
    | CalcMsg CalcEngine.Msg -- formerly UI.Msg
    -- | Initialize
    | ReceiveHints (List String)
    | EditorContentChanged String
    | RequestHints String
    | InitEditor




-- Update-
-- no need to add xModel to update args in Main, it is already in model here
-- in component must add xModel to update in order to send/receive xModel to/from Main

update : Msg -> Result Error Env -> Model -> (Model, Result Error Env , Cmd Msg)
update msg prevEnv model =
    case msg of
        SpreadsheetUIMsg subMsg ->
            let
                -- update the spreadsheetUIModel and xModel from the subMsg action
                curCalcModel = model.calcModel 
                curEnv = prevEnv
                curXModel = getCurXModelFromEnv curEnv
                (updatedSpreadsheetUIModel, updatedXModel, cmd) = SpreadsheetUI.update subMsg model.spreadsheetUIModel curXModel
            in
            case curXModel.datasetToRecalc of
                Just datasetName ->
                    let
                        nextMsg = 
                            if curCalcModel.datasetRef == datasetName then 
                                CalcEngine.EvalFormulas
                            else
                                CalcEngine.NoOp
                    in
                    ({ model 
                        | spreadsheetUIModel = updatedSpreadsheetUIModel
                     }
                    , (CalcEngine.setXModelToEnv curEnv updatedXModel)
                    , Cmd.batch [ Cmd.map SpreadsheetUIMsg cmd
                                , Cmd.map CalcMsg ( Task.perform (\_ -> nextMsg) (Task.succeed ()) )
                                ])
                Nothing ->
                    ({ model 
                        | spreadsheetUIModel = updatedSpreadsheetUIModel
                        }
                        , (CalcEngine.setXModelToEnv curEnv updatedXModel)
                        , Cmd.map SpreadsheetUIMsg cmd) 

  
        DnDTrayMsg subMsg ->
            case subMsg of
                DnDTray.DnDTrayDropdownMsg dropdownId dropdownMsg ->
                    let
                        -- Forward the dropdown message to DnDTray.update and handle the response
                        (updatedDndGroups, cmd) = DnDTray.update (DnDTray.DnDTrayDropdownMsg dropdownId dropdownMsg) model.dndTrayModel
                    in
                    ({ model | dndTrayModel = updatedDndGroups }
                    , prevEnv
                    , Cmd.map DnDTrayMsg cmd)

                DnDTray.DnDTrayOptionPicked dropdownId option ->
                    -- Handle option picked and update the dataset view
                    -- pivot update copied from DnDTray.DnDMsg 
                    let
                        (updatedDndGroups, cmd) = DnDTray.update subMsg model.dndTrayModel
                        -- updates for new dropdoen selection
                        updatedDataview = XView.updateDropdownOption dropdownId (Maybe.withDefault "" option) model.spreadsheetUIModel.curDatasetView
                        curSpreadsheetModel = model.spreadsheetUIModel
                        -- first round of update to set thetrays and  new datasetView 
                        updatedSpreadsheetUIModel = 
                            { curSpreadsheetModel 
                                | curDatasetView = updatedDataview
                            }
                        updatedModel = { model 
                            | spreadsheetUIModel = updatedSpreadsheetUIModel
                            -- needed to keep dropdown selection
                            , dndTrayModel = updatedDndGroups
                            }

                        -- removed this passage that initializes pageTray coords to first
                        --  updatedSpreadsheetUIModel = updateDatasetViewFromTrays updatedModel -- check pageTray overwrite
                        -- refresh spreadsheet data and index
                        curXModel = prevEnv |> CalcEngine.getXModelFromEnv |> Maybe.withDefault XModel.emptyXModel
                        (newSpreadsheet, newIndex) = 
                            SpreadsheetUI.getCurrentSpreadsheetAndIndexFromView updatedSpreadsheetUIModel curXModel
                        -- updates cellsUI with new spreadsheet
                        updatedCellsUI = SpreadsheetUI.updateCellsUI updatedSpreadsheetUIModel.cellsUI newSpreadsheet
                        updatedSpreadsheetUIModelBis = 
                            { updatedSpreadsheetUIModel | spreadsheet = newSpreadsheet, spreadsheetIndex = newIndex
                            -- aggiorna lo spreadsheet unica colonna non cambia colHeaders
                            , cellsUI =  updatedCellsUI
                            }

                    in
                    -- Debug.log ("(dropdownId, option)" ++ Debug.toString (dropdownId, option))
                    -- Debug.log ("updatedDataview" ++ Debug.toString updatedDataview.pageTray)
                    ({ updatedModel   
                        | spreadsheetUIModel = updatedSpreadsheetUIModelBis 
                        --, dndTrayModel = updatedDndGroups
                    }
                    -- cmd restituito da DnDTray.update chiamato sopra
                    , prevEnv
                    , Cmd.map DnDTrayMsg cmd) 

                DnDTray.DnDMsg _ ->
                    -- Handle other DnDTray messages as before
                    let
                        -- passa l'update event al model di DnDTray e riceve il cmd da eseguire
                        -- lo stesso cmd viene eseguito alla fine
                        -- qui subito aggiorna le info per camnbiare i Tray
                        (updatedDndGroups, cmd) = DnDTray.update subMsg model.dndTrayModel
                        -- con i Tray cambiati parte il reshape della pivot table
                        updatedModel = { model | dndTrayModel = updatedDndGroups }
                        -- se uso updatedSpreadsheetUIModel funziona
                        updatedSpreadsheetUIModel = updateDatasetViewFromTrays updatedModel prevEnv

                        --(newSpreadsheet, newIndex) = SpreadsheetUI.getCurrentSpreadsheetAndIndexFromTable updatedSpreadsheetUIModel
                        curXModel = prevEnv |> CalcEngine.getXModelFromEnv |> Maybe.withDefault XModel.emptyXModel
                        (newSpreadsheet, newIndex) = 
                            SpreadsheetUI.getCurrentSpreadsheetAndIndexFromView updatedSpreadsheetUIModel curXModel

                        updatedSpreadsheetUIModelBis = 
                            let
                                nrCols = Array2D.columns newSpreadsheet
                                nrRows = Array2D.rows newSpreadsheet
                            in 
                            { updatedSpreadsheetUIModel | spreadsheet = newSpreadsheet, spreadsheetIndex = newIndex
                            -- aggiorna lo spreadsheet unica colonna non cambia colHeaders
                            , cellsUI = (SpreadsheetUI.updateCellsUI updatedSpreadsheetUIModel.cellsUI newSpreadsheet)
                            , nrCols = nrCols
                            , nrRows = nrRows
                            , columnWidths = Array.repeat nrCols updatedSpreadsheetUIModel.defaultColumnWidth
                            }
                    in
                    -- Debug.log ("DnDMsg handled" ++ Debug.toString subMsg)
                    ({ updatedModel   | spreadsheetUIModel = updatedSpreadsheetUIModelBis 
                    }
                    -- cmd restituito da DnDTray.update chiamato sopra
                    , prevEnv
                    , Cmd.map DnDTrayMsg cmd) -- con Cmd.none non funziona il drag and drop

        CalcMsg calcMsg ->
            let
                (updatedCalcModel, newEnv, calcCmd) = CalcEngine.update calcMsg model.calcModel prevEnv
                curDatasetName = model.spreadsheetUIModel.curDataset.ref
                updatedXModel = CalcEngine.getXModelFromEnv newEnv |> Maybe.withDefault XModel.emptyXModel
                curDataset = XModel.getDatasetByRef curDatasetName updatedXModel.datasets |> Maybe.withDefault XModel.emptyDataset
                updatedSpreadsheetUIModel = SpreadsheetUI.updateSpreadsheetFromXModel model.spreadsheetUIModel updatedXModel curDataset
            in
            -- Debug.log ("updatedDataset.data" ++ Debug.toString curDataset)
            (-- add updateSpreadsheetUIModel
                { model 
                | spreadsheetUIModel = updatedSpreadsheetUIModel
                , calcModel = updatedCalcModel 
             }
             , newEnv
             , Cmd.map CalcMsg calcCmd)

        EditorContentChanged content ->
            let
                prevCalcModel = model.calcModel
                updatedCalcModel = { prevCalcModel | input = content }
            in
            ( { model | calcModel = updatedCalcModel }
              , prevEnv
              , Cmd.none )
        RequestHints word ->
            let
                curXModel = getCurXModelFromEnv prevEnv
                hints = getHints curXModel word
            in
            (model, prevEnv, sendHintsToJs hints)

        ReceiveHints hints ->
            ({ model | hints = hints }, prevEnv, Cmd.none)

        InitEditor ->
            ( model, prevEnv, Cmd.none )


sendHintsToJs : List String -> Cmd Msg
sendHintsToJs hints =
    let
        encodedHints = Json.Encode.list Json.Encode.string hints
    in
    Ports.receiveHints encodedHints

getCurXModelFromEnv : Result Error Env -> XModel
getCurXModelFromEnv env  = env |> CalcEngine.getXModelFromEnv |> Maybe.withDefault XModel.emptyXModel
-- add coords like in expression parsing!!!
getHints : XModel -> String -> List String
getHints xModel word =
    let
        parts = FormulaParser.parseHierarchicalName word
    in
    case parts of
        Ok (datasetRef, "", [] ) ->
            List.filter (String.startsWith datasetRef) xModel.datasetRefs
                |> List.map (\ref -> FormulaParser.lowerFirst ref )

        Ok (datasetRef, dataArrayRef, []) ->
            case Dict.get datasetRef xModel.datasets of
                Just dataset ->
                    List.filter (String.startsWith dataArrayRef) dataset.dataArrayRefs
                        |> List.map (\ref -> (FormulaParser.lowerFirst datasetRef) 
                            ++ "__" ++ ref)
                Nothing ->
                    []

        Ok (datasetRef , dataArrayRef , dimRefs) ->
            case Dict.get datasetRef xModel.datasets of
                Just dataset ->
                    let
                        maybeDataArrayWithDims = XModel.getDataArrayWithDimsFromXModel 
                            xModel datasetRef dataArrayRef
                    in
                    case maybeDataArrayWithDims of
                        Just dataArray ->
                            let
                                -- get last element of dimRefs
                                dimRefLast = List.head (List.reverse dimRefs)
                                dimRefPrev = (List.drop 1 (List.reverse dimRefs)) |> List.reverse
                                -- if dimRefPrev
                                dimRefPrevStr = 
                                    if dimRefPrev == [] then
                                        ""
                                    else
                                        "_" ++ (String.join "_" dimRefPrev)
                            in
                            case (dataArray.localDimRefs, dimRefLast) of
                                (Just localDimRefs, Just dimLast) ->
                                    List.filter (String.startsWith dimLast) localDimRefs
                                        |> List.map (\ref -> (FormulaParser.lowerFirst datasetRef) 
                                            ++ "__" ++ dataArrayRef ++ dimRefPrevStr ++ "_" ++ ref)
                                (_, _) ->
                                    []
                        Nothing ->
                            []
                Nothing ->
                    []

        _ ->
            []

-- used in DnDTrayMsg subMsg, returns updated SpreadsheetUI.Model set to model.spreadsheetUIModel
-- then continues with update cellsUI from spreadsheetUI
-- rationalize to avoid duplication of steps in update or use of stale model data modified by update
updateDatasetViewFromTrays : Model -> Result Error Env -> SpreadsheetUI.Model
updateDatasetViewFromTrays model curEnv =
    let
        -- common step get from trays the names of the pages, rows and columns
        -- to trigger when tokens are moved across trays
        pageNames = DnDTray.getPageNames model.dndTrayModel.trayData
        rowNames = DnDTray.getRowNames model.dndTrayModel.trayData
        colNames = DnDTray.getColNames model.dndTrayModel.trayData

        -- set shapes and data as required by XArray and update model.datasetView
        curXModel = curEnv |> CalcEngine.getXModelFromEnv |> Maybe.withDefault XModel.emptyXModel
        updatedDataview = XView.updateDatasetViewTrays curXModel.dims
            model.spreadsheetUIModel.curDataset model.spreadsheetUIModel.curDatasetView pageNames rowNames colNames 
      
        -- gets current spreadsheetUI model
        curSpreadsheetModel = model.spreadsheetUIModel
    in
    -- returns updated spreadsheetUI model with shape settings for MyPivotTable and datasetView with shape and data
    { curSpreadsheetModel 
        | curDatasetView = updatedDataview
    }


-- View
view : Result Error Env -> Model -> Element Msg
view curEnv model =
    let
        modalView = Element.map SpreadsheetUIMsg <| SpreadsheetUI.spreadsheetModalView model.spreadsheetUIModel
        lenSpreadsheetWidth = 1200 -- 600px
        curXModel = curEnv |> CalcEngine.getXModelFromEnv |> Maybe.withDefault XModel.emptyXModel
        editorElement =
                Element.html <| Html.node "code-mirror-editor"
                    [ HtmlAttr.attribute "data-initial-value" model.calcModel.input
                    , Html.Events.on "contentChanged" (Decode.map EditorContentChanged (Decode.at [ "detail" ] Decode.string))
                    ] []

    in 
    column [ inFront modalView ] -- messi 600px larghezza sheet si adatta se superiore no se inferiore
        [ 
        -- title and dim trays
        column [] -- styles of trays set in DnDTray group styles
        [ viewTitle model
            , column [ UiFont.size 14, width (px lenSpreadsheetWidth) ] -- cannot set dynamically to max width of container elements
                [ Element.map DnDTrayMsg <| DnDTray.pageTrayView model.dndTrayModel
                -- brought row tray and column tray together for easier reshaping
                , row [ width fill, height (px 120) ] -- no shrink loses row headers
                -- in DnDTray all trays are set to width fill
                    [ Element.map DnDTrayMsg <| DnDTray.rowTrayView model.dndTrayModel
                    , Element.map DnDTrayMsg <| DnDTray.columnTrayView model.dndTrayModel
                    , Element.map DnDTrayMsg <| DnDTray.ghostView model.dndTrayModel.dnd model.dndTrayModel.trayData
                    ]
                ]
        ]
        -- spreadsheet in pivot table
        , row [ width (px lenSpreadsheetWidth), height shrink ]
          [ Element.map SpreadsheetUIMsg 
            <| SpreadsheetUI.viewPivotTableFromSpreadsheetView model.spreadsheetUIModel curXModel
          ]
        , column [ width (px lenSpreadsheetWidth), height shrink ]
             [ Element.map CalcMsg <| CalcEngine.viewCommands 
             , editorElement
             , Element.map CalcMsg <| CalcEngine.viewConsole model.calcModel 
             ]
        ]



        




stickyTopHeaderAttrs : List (Attribute msg)
stickyTopHeaderAttrs =
    [ Element.htmlAttribute (style "position" "sticky")
    , Element.htmlAttribute (style "top" "0px")
    , Element.htmlAttribute (style "z-index" "3")
    ]
stickyLeftHeaderAttrs : List (Attribute msg)
stickyLeftHeaderAttrs =
    [ Element.htmlAttribute (style "position" "sticky")
    , Element.htmlAttribute (style "left" "0px") 
    , Element.htmlAttribute (style "z-index" "3")
    ]
viewTitle : Model -> Element Msg
viewTitle model =
    let
        titleText = model.spreadsheetUIModel.curDatasetView.name
    in
    el ([ UiFont.bold
        , UiFont.size 20
        , paddingEach {top=10, bottom=4, left=0, right=0}
        --, alignLeft
        --, centerY
        , height (px 30)
        , width fill --(px 600)
        , Background.color MyColors.white
        ] ++ stickyLeftHeaderAttrs)
        <| text titleText


-- presa da Korban p. 121
htmlAttributes : List (Html.Attribute Msg) -> List (Attribute Msg) 
htmlAttributes =
    List.map htmlAttribute


init : Result Error Env -> DatasetRef -> (Model, Result Error Env , Cmd Msg)
init env datasetRef =
    let
        model = initialModel env datasetRef
        initialFocusCmd = Cmd.none -- Cmd.map SpreadsheetUIMsg SpreadsheetUI.focusA1
        initializeEditorCmd = Ports.initializeEditor ("editor", model.calcModel.input)
        initEditorUpdateMsg = AppUtil.cmdMsg InitEditor
    in
    ( {model | editorInitialized = False }
    , env
    , Cmd.batch [initialFocusCmd, initializeEditorCmd, initEditorUpdateMsg]
    )



subscriptions : Model -> Sub Msg
subscriptions model =
    Sub.batch
        [ Sub.map DnDTrayMsg (DnDTray.subscriptions model.dndTrayModel)
        , Sub.map SpreadsheetUIMsg (SpreadsheetUI.subscriptions model.spreadsheetUIModel)
        , Ports.editorContentChanged EditorContentChanged
        , Ports.requestHints RequestHints
        ]


-- main : Program () Model Msg
-- main =
--     Browser.element
--         { init = init
--         , update = update
--         , view = view
--         , subscriptions = subscriptions
--         }



