module DatasetPage exposing (..)

-- former single page Main.elm
-- TO BUILD
-- remove /build folder
-- > make all
-- TO RUN
-- > elm-watch hot
-- NB: to change the executed js comment/uncomment in the index.html
-- ./dist/ui.js is generated by Makefile, from console: make all (after deleting /build folder)
-- app.js is generated by elm make src/Main.elm --output=app.js
-- elm-watch hot works with both (I assume it goes after index.html in the running folder)
-- spreadsheetUI and pivot tables
-- import PersonValuePivot exposing (..)
-- Drag and drop
-- Dropdown
-- XModel and CalcEngine
-- elm-interpreter
-- UI

import AppUtil exposing (cmdMsg, myLog)
import Array
import Array2D
import Browser.Navigation as Navigation
import CalcEngine exposing (Msg(..))
import DnDTray exposing (..)
import Dropdown exposing (Msg(..))
import Element exposing (..)
import Element.Background as Background
import Element.Border as Border
import Element.Font as UiFont
import Element.Input as Input
import FastDict as Dict exposing (Dict)
import Html
import Html.Attributes as HtmlAttr exposing (style)
import Html.Events
import Json.Decode as Decode
import MyColors exposing (..)
import Platform.Cmd as Cmd
import Platform.Sub as Sub
import Ports
import SpreadsheetUI exposing (..)
import Time exposing (now)
import Types exposing (CallTree(..), Env, Error(..), Value(..))
import TypesJavascript exposing (Editor)
import TypesXModel exposing (..)
import UI.Theme as Theme
import UiWidgets exposing (tooltip, lightTooltip)
import XModel
import XView
import Core.Basics exposing (le)
import CalcEngine exposing (setXModelToEnv)
import CalcEngine exposing (getXModelFromEnv)


type alias Model =
    { spreadsheetUIModel : SpreadsheetUI.Model
    , calcModel : CalcEngine.Model
    , autoRecalc : Bool
    , hints : List String
    , editorId : String
    , showFormulaEditor : Bool
    , editor : Editor
    , showPivotReshaper : Bool
    , showLogs : Bool
    }


initialModel : Result Error Env -> DatasetRef -> Model
initialModel env datasetRef =
    let
        initialShowFormulaEditor =
            False

        initialShowPivotReshaper =
            True

        initialShowLogs =
            True

        initialCalcModel =
            CalcEngine.initialModel env datasetRef

        initialXModel =
            CalcEngine.getXModelFromEnv env |> Maybe.withDefault XModel.emptyXModel

        initialSpreadsheetUIModel =
            SpreadsheetUI.initialModel initialXModel datasetRef


        initialEditorId =
            "editor-" ++ datasetRef
        initialEditor =
            { id = initialEditorId, editorType = "formula", initialized = False }
    in
    { spreadsheetUIModel = initialSpreadsheetUIModel
    , calcModel = initialCalcModel
    , autoRecalc = False
    , hints = []
    , editorId = initialEditorId
    , editor = initialEditor
    , showFormulaEditor = initialShowFormulaEditor
    , showPivotReshaper = initialShowPivotReshaper
    , showLogs = initialShowLogs
    }


type Msg
    = SpreadsheetUIMsg SpreadsheetUI.Msg
    | CalcMsg CalcEngine.Msg -- formerly UI.Msg
      -- | Initialize
    | ReceiveHints { editorId : String, hints : List String } -- Include editorId
    | FormulaContentChanged { editorId : String, content : String }
    | RequestHints { editorId : String, word : String }
    | InitEditor
    | OpenDataset Navigation.Key String
    | TriggerPageReload
    | ToggleFormulaEditor
    | TogglePivotReshaper


type alias Models =
    { calc : CalcEngine.Model, x : XModel, ui : SpreadsheetUI.Model }



-- Update-
-- no need to add xModel to update args in Main, it is already in model here
-- in component must add xModel to update in order to send/receive xModel to/from Main


update : Msg -> Result Error Env -> Model -> ( Model, Result Error Env, Cmd Msg )
update msg prevEnv model =
    case myLog "SpreadsheetUIMsg in DatasetPage" msg of
        SpreadsheetUIMsg subMsg ->
            case subMsg of
                DnDTrayMsg trayMsg ->
                    let
                        ( sUiModel, xModel, dndMsg ) =
                            SpreadsheetUI.update 
                                subMsg 
                                model.spreadsheetUIModel 
                                (getXModelFromEnv prevEnv |> Maybe.withDefault XModel.emptyXModel)
                    in
                    ( { model | spreadsheetUIModel = sUiModel }
                    , setXModelToEnv prevEnv xModel
                    , Cmd.map SpreadsheetUIMsg dndMsg
                    )
                _ -> -- other msgs alreadt handled in DatasetPage.update previous version
                    
                    let
                        curCalcModel = model.calcModel
                        curEnv = prevEnv
                        curXModel = getCurXModelFromEnv curEnv

                        -- Update the spreadsheetUIModel and xModel from the subMsg action in SpreadsheetUI
                        (sUiModel1, xModel1, sUiCmd1) =
                            SpreadsheetUI.update subMsg model.spreadsheetUIModel curXModel

                        -- Function to handle recalculation if needed
                        handleRecalc : List DatasetRef -> CalcEngine.Model -> XModel -> SpreadsheetUI.Model -> (Models, List (Cmd Msg))
                        handleRecalc datasetRefs calcModel xModel sUiModel =
                            case List.filter (\r -> r == calcModel.datasetRef) datasetRefs |> List.head of
                                Just datasetName ->
                                    let
                                        envWithChangedXModel = CalcEngine.setXModelToEnv curEnv xModel
                                        (calcModelCalculated, envCalculated, calcCmd) =
                                            CalcEngine.update CalcEngine.EvalFormulas calcModel envWithChangedXModel
                                        xModelCalculated = CalcEngine.getXModelFromEnv envCalculated |> Maybe.withDefault XModel.emptyXModel
                                        (sUiModelRefresh, xModelRefresh, sUiCmdRefresh) =
                                            SpreadsheetUI.update SpreadsheetUI.RefreshFromXModel sUiModel xModelCalculated
                                        curCalcCmds = [Cmd.map CalcMsg calcCmd, Cmd.map SpreadsheetUIMsg sUiCmdRefresh]
                                        curModels = { calc = calcModelCalculated, x = xModelRefresh, ui = sUiModelRefresh }
                                    in
                                    (curModels, curCalcCmds)

                                Nothing ->
                                    ({ calc = calcModel, x = xModel, ui = sUiModel }, [Cmd.none])

                        (models, recalcCmds) = handleRecalc xModel1.datasetsToRecalc curCalcModel xModel1 sUiModel1
                        curDndModel = models.ui.dndTrayModel
                        updatedTrayData = models.ui.sheetUIData.trayData
                        spreadsheetUIModelPreDnD = models.ui
                        updatedSpreadsheetUIModel = { spreadsheetUIModelPreDnD | dndTrayModel = { curDndModel | trayData = updatedTrayData } }

                        finalModel = { model | spreadsheetUIModel = updatedSpreadsheetUIModel, calcModel = models.calc }
                        finalEnv = CalcEngine.setXModelToEnv curEnv models.x
                        finalCmds = [Cmd.map SpreadsheetUIMsg sUiCmd1] ++ recalcCmds
                    in
                    (finalModel, finalEnv, Cmd.batch finalCmds)
        -- SpreadsheetUIMsg subMsg ->
        --     let
        --         curCalcModel =
        --             model.calcModel

        --         curEnv =
        --             prevEnv

        --         curXModel =
        --             getCurXModelFromEnv curEnv

        --         -- Update the spreadsheetUIModel and xModel from the subMsg action in SpreadsheetUI
        --         ( sUiModel1, xModel1, sUiCmd1 ) =
        --             SpreadsheetUI.update subMsg model.spreadsheetUIModel curXModel

        --         -- Function to handle recalculation if needed
        --         --  RECALC TRIGGERING MOVED TO MAIN EnvUpdated but still needed here, TODO: check if needed
        --         handleRecalc : List DatasetRef -> CalcEngine.Model -> XModel -> SpreadsheetUI.Model -> ( Models, List (Cmd Msg) )
        --         handleRecalc datasetRefs calcModel xModel sUiModel =
        --             case List.filter (\r -> r == calcModel.datasetRef) datasetRefs |> List.head of
        --                 Just datasetName ->
        --                     -- calcModel.datasetRef is in datasetsToRecalc
        --                     let
        --                         -- SaveCell populates datasetsToRecalc
        --                         envWithChangedXModel =
        --                             CalcEngine.setXModelToEnv curEnv xModel

        --                         -- trigger recalculation, disabled, moved to EnvUpdated
        --                         ( calcModelCalculated, envCalculated, calcCmd ) =
        --                             CalcEngine.update CalcEngine.EvalFormulas calcModel envWithChangedXModel

        --                         xModelCalculated =
        --                             CalcEngine.getXModelFromEnv envCalculated |> Maybe.withDefault XModel.emptyXModel

        --                         -- Step 2: Update SpreadsheetUI with updated XModel
        --                         ( sUiModelRefresh, xModelRefresh, sUiCmdRefresh ) =
        --                             SpreadsheetUI.update
        --                                 SpreadsheetUI.RefreshFromXModel
        --                                 sUiModel
        --                                 xModelCalculated

        --                         curCalcCmds =
        --                             [ Cmd.map CalcMsg calcCmd, Cmd.map SpreadsheetUIMsg sUiCmdRefresh ]

        --                         curModels =
        --                             { calc = calcModelCalculated, x = xModelRefresh, ui = sUiModelRefresh }
        --                     in
        --                     ( curModels, curCalcCmds )

        --                 Nothing ->
        --                     -- No recalculation needed, return the same models and no command
        --                     ( { calc = calcModel, x = xModel, ui = sUiModel }, [ Cmd.none ] )

        --         -- end of handleRecalc
        --         ( models, recalcCmds ) =
        --             handleRecalc xModel1.datasetsToRecalc curCalcModel xModel1 sUiModel1
        --         curDndModel =
        --             model.spreadsheetUIModel.dndTrayModel
        --         updatedTrayData =
        --             models.ui.sheetUIData.trayData
        --         spreadsheetUIModelPreDnD =
        --             models.ui 
        --         updatedSpreadsheetUIModel =
        --             { spreadsheetUIModelPreDnD 
        --                 | dndTrayModel = { curDndModel | trayData = updatedTrayData }
        --             }

        --         --({calc=curCalcModel, x=xModel1, ui=sUiModel1}, [Cmd.none])  -- no recalc
        --         finalModel =
        --             { model
        --                 | spreadsheetUIModel =  updatedSpreadsheetUIModel
        --                 , calcModel = models.calc
        --             }

        --         finalEnv =
        --             CalcEngine.setXModelToEnv curEnv models.x

        --         finalCmds =
        --             [ Cmd.map SpreadsheetUIMsg sUiCmd1 ] ++ recalcCmds
        --     in
        --     -- Debug.log ("NewHeaderTree: " ++ Debug.toString models.ui.sheetUIData)
        --     ( finalModel, finalEnv, Cmd.batch finalCmds )

        -- con Cmd.none non funziona il drag and drop
        CalcMsg calcMsg ->
            let
                ( updatedCalcModel, newEnv, calcCmd ) =
                    CalcEngine.update calcMsg model.calcModel prevEnv

                curDatasetName =
                    model.spreadsheetUIModel.curDataset.ref

                updatedXModel =
                    CalcEngine.getXModelFromEnv newEnv |> Maybe.withDefault XModel.emptyXModel

                curDataset =
                    XModel.getDatasetByRef curDatasetName updatedXModel.datasets |> Maybe.withDefault XModel.emptyDataset

                updatedSpreadsheetUIModel =
                    SpreadsheetUI.updateSpreadsheetFromXModel model.spreadsheetUIModel updatedXModel curDataset
            in
            -- Debug.log ("updatedDataset.data" ++ Debug.toString curDataset)
            ( -- add updateSpreadsheetUIModel
              { model
                | spreadsheetUIModel = updatedSpreadsheetUIModel
                , calcModel = updatedCalcModel
              }
            , newEnv
            , Cmd.map CalcMsg calcCmd
            )

        FormulaContentChanged { editorId , content } ->
            if editorId == model.editorId then
                    let
                        prevCalcModel =
                            model.calcModel

                        updatedCalcModel =
                            { prevCalcModel | formulaInput = content }
                    in
                    ( { model | calcModel = updatedCalcModel }
                    , prevEnv
                    , Cmd.none
                    )
            else
                ( model, prevEnv, Cmd.none )

        RequestHints { editorId, word } ->
            let
                curXModel =
                    getCurXModelFromEnv prevEnv

                hints =
                    getHints curXModel model.calcModel.datasetRef word

                editorIdElm =
                    model.editorId
            in
            if editorId == editorIdElm then
                ( model, prevEnv, sendHintsToJs editorId hints )

            else
                ( model
                , prevEnv
                  -- , sendHintsToJs editorIdElm ["mismatched editorIds: js=" ++ editorId ++ " and elm=" ++ editorIdElm]
                , Cmd.none
                )

        ReceiveHints { editorId, hints } ->
            if editorId == model.editorId then
                ( { model | hints = hints }, prevEnv, Cmd.none )

            else
                ( model, prevEnv, Cmd.none )

        InitEditor ->
            -- editor init moved to init as direct port call
            ( model, prevEnv, Cmd.none )

        OpenDataset key datasetName ->
            ( model
            , prevEnv
            , Cmd.batch [ navigateToDataset key datasetName, cmdMsg TriggerPageReload ]
            )

        TriggerPageReload ->
            --( model, prevEnv, Ports.reloadPage () )
            ( model, prevEnv, Cmd.none )

        ToggleFormulaEditor ->
            let
                newShowFormulaEditor = not model.showFormulaEditor
                curEditor = model.editor
                cmd =
                    if newShowFormulaEditor && not model.editor.initialized then
                        Ports.initializeEditor model.editor.id
                    else if not newShowFormulaEditor && model.editor.initialized then
                        Ports.disposeEditor model.editor.id
                    else
                        Cmd.none
                newEditor =
                    { curEditor | initialized = newShowFormulaEditor }
            in
            ( { model | showFormulaEditor = newShowFormulaEditor, editor = newEditor }
            , prevEnv
            , cmd )


        TogglePivotReshaper ->
            ( { model | showPivotReshaper = not model.showPivotReshaper }, prevEnv, Cmd.none )


sendHintsToJs : String -> List { label : String } -> Cmd Msg
sendHintsToJs editorId hints =
    let
        payload =
            { editorId = editorId, hints = hints }
    in
    -- Debug.log ("sendHintsToJs payload" ++ Debug.toString payload)
    Ports.receiveHints payload


getHints : XModel -> DatasetRef -> String -> List { label : String }
getHints xModel datasetRef word =
    XModel.promptCoordsForPartialRangeName xModel datasetRef word


getCurXModelFromEnv : Result Error Env -> XModel
getCurXModelFromEnv env =
    env |> CalcEngine.getXModelFromEnv |> Maybe.withDefault XModel.emptyXModel



-- add coords like in expression parsing!!!
-- used in DnDTrayMsg subMsg, returns updated SpreadsheetUI.Model set to model.spreadsheetUIModel
-- then continues with update cellsUI from spreadsheetUI
-- rationalize to avoid duplication of steps in update or use of stale model data modified by update




-- View
-- Helper function to generate the navigation menu


viewNavMenu : List String -> Element Msg
viewNavMenu datasetNames =
    row [ spacing 10, padding 10 ]
        (List.map
            (\name ->
                link
                    [ UiFont.color blue, UiFont.family [ UiFont.typeface "Raleway", UiFont.sansSerif ] ]
                    { url = "/#/dataset/" ++ name
                    , label = text name
                    }
            )
            datasetNames
        )



-- alternative to navMenu
-- Helper function to generate the navigation tabs


viewDatasetNavTabs : Navigation.Key -> List String -> String -> Element Msg
viewDatasetNavTabs key datasetNames currentDataset =
    row [ spacing 10, padding 10 ]
        (List.map
            (\name ->
                let
                    isSelected =
                        name == currentDataset

                    tabStyle =
                        [ UiFont.family [ UiFont.typeface "Raleway", UiFont.sansSerif ]
                        , UiFont.color
                            (if isSelected then
                                darkCharcoal

                             else
                                darkGray
                            )
                        , paddingEach { top = 8, right = 16, bottom = 8, left = 16 }
                        , Border.color
                            (if isSelected then
                                darkGray

                             else
                                lightGray
                            )
                        , Background.color
                            (if isSelected then
                                lightGray

                             else
                                white
                            )
                        , if isSelected then
                            UiFont.bold

                          else
                            UiFont.light
                        , Border.rounded 4
                        , Border.solid
                        , Border.width
                            (if isSelected then
                                2

                             else
                                1
                            )
                        , if isSelected then
                            UiFont.bold

                          else
                            UiFont.regular
                        ]
                in
                Element.el tabStyle
                    (Input.button []
                        { onPress = Just (OpenDataset key name), label = text name }
                    )
            )
            datasetNames
        )


navigateToDataset : Navigation.Key -> String -> Cmd Msg
navigateToDataset key datasetName =
    let
        url =
            "/#/dataset/" ++ datasetName
    in
    Navigation.pushUrl key url



-- shows dataset nav toolbar, trays, spreadsheet, formula editor, logs





-- used in elm-foldbook, without logo and title 


viewSheet : Result Error Env -> Model -> Element Msg
viewSheet curEnv model =
    let

        lenSpreadsheetWidth =
            Array.foldl
                (\x y -> x + y)
                0
                ( Array.append model.spreadsheetUIModel.rowHeaderWidths model.spreadsheetUIModel.colWidths)
            |> (+) model.spreadsheetUIModel.topRightHeaderWidth


        spreadsheetView =
            SpreadsheetUI.viewSpreadsheetUI model.spreadsheetUIModel
    in
    column [ ]
        -- messi 600px larghezza sheet si adatta se superiore no se inferiore
        [ -- title and dim trays
          column [ width fill ]
            -- styles of trays set in DnDTray group styles
            -- spreadsheet in pivot table
            [  -- AppUtil.myLog ("pagetray" ++ Debug.toString model.spreadsheetUIModel.curDatasetView.pageTray)
                --if model.spreadsheetUIModel.curDatasetView.pageTray /= [] then
              Element.map SpreadsheetUIMsg 
                <| SpreadsheetUI.viewPivotReshaper 
                    model.spreadsheetUIModel 
                    lenSpreadsheetWidth 
                    model.showPivotReshaper--(lenSpreadsheetWidth |> toFloat |> (*) 0.5 >> round)
            , row 
                [ width (px lenSpreadsheetWidth), height shrink 
                --, below (viewPivotReshaper model lenSpreadsheetWidth) -- NO, overlaps
                ]
                [ Element.map SpreadsheetUIMsg spreadsheetView ]
            , column [ width (px lenSpreadsheetWidth), height shrink ]
                [ row [ spacing 10, width fill ]
                    [ buttonToggleFormulaEditor model 40
                    --, buttonRecalculate model 40
                    , buttonUpdateFormulas model 40
                    --Element.map CalcMsg <| CalcEngine.viewCommands
                    --, buttonGroupFormulaPivot
                    ]
                , viewFormulaEditor model lenSpreadsheetWidth

                -- logging calculation messages, activated via mode.showLogs in Main.init
                , viewLogs model
                ]
            ]
        ]



viewFormulaEditor : Model -> Int -> Element Msg
viewFormulaEditor model spreadsheetWidth =
    let
        editorElement editorId input =
            case editorId of
                Just editorIdJust ->
                    Element.html <|
                        Html.node "code-mirror-formula-editor"
                            [ HtmlAttr.attribute "data-initial-value" input
                            , HtmlAttr.attribute "id" editorIdJust
                            , Html.Events.on "formulaContentChanged" 
                                (Decode.map FormulaContentChanged 
                                    (Decode.at [ "detail" ] 
                                        (Decode.map2 (\editorIdArg contentArg -> 
                                            { editorId = editorIdArg, content = contentArg }) 
                                            (Decode.field "editorId" Decode.string) (Decode.field "content" Decode.string))))
                            ]
                            []

                Nothing ->
                    Element.none
    in
    if model.showFormulaEditor then
        column [ padding 20, spacing 10, width (px (max 1200 spreadsheetWidth))]
            [ row ([ UiFont.size 24, UiFont.bold, width fill ] ++ noWrapAttributes) [ text "Formula Editor" ]
            , el [ UiFont.size 16, width fill ] (editorElement (Just model.editorId) model.calcModel.formulaInput)
            ]

    else
        Element.none

-- USED FOR STANDALONE SHEETS, IN MARKUP FOLDBOOK USES viewSheet
view : Navigation.Key -> Result Error Env -> Model -> Element Msg
view key curEnv model =
    let

        lenSpreadsheetWidth =
            1200

        -- 600px
        curXModel =
            curEnv |> CalcEngine.getXModelFromEnv |> Maybe.withDefault XModel.emptyXModel

        spreadsheetView =
            SpreadsheetUI.viewSpreadsheetUI model.spreadsheetUIModel

        datasetNames =
            curXModel.datasetRefs
    in
    column [  ]
        -- messi 600px larghezza sheet si adatta se superiore no se inferiore
        [ -- title and dim trays
          column []
            -- styles of trays set in DnDTray group styles
            [ row [ width fill, spacing 6 ] [ logo, viewTitle curXModel.modelRef ]
            , viewDatasetNavTabs key datasetNames model.spreadsheetUIModel.curDataset.ref

            --, (viewNavMenu datasetNames)
            ]

        -- spreadsheet in pivot table
        , row [ width (px lenSpreadsheetWidth), height shrink ]
            [ Element.map SpreadsheetUIMsg spreadsheetView ]
        , column [ width (px lenSpreadsheetWidth), height shrink ]
            [ row [ spacing 10 ]
                [ Element.map CalcMsg <| CalcEngine.viewCommands
                , buttonGroupFormulaPivot
                ]
            , Element.map SpreadsheetUIMsg 
                <| SpreadsheetUI.viewPivotReshaper model.spreadsheetUIModel 
                    (lenSpreadsheetWidth |> toFloat |> (*) 0.5 >> round)
                    model.showPivotReshaper
            , viewFormulaEditor model lenSpreadsheetWidth

            -- logging calculation messages, activated via mode.showLogs in Main.init
            , viewLogs model
            ]
        ]
-- helper functions
noWrapAttributes : List (Attribute msg)
noWrapAttributes =
    [ Element.htmlAttribute (style "white-space" "nowrap")

    -- , Element.htmlAttribute (style "overflow" "hidden")
    -- , Element.htmlAttribute (style "text-overflow" "ellipsis")
    ]


buttonGroupFormulaPivot : Element Msg
buttonGroupFormulaPivot =
    Theme.boxRow "Show/Hide"
        [ width <| fillPortion 1, alignTop ]
        [ Theme.button [ width shrink ]
            { onPress = Just ToggleFormulaEditor
            , label = text "Formula Editor"
            }
        , Theme.button [ width shrink ]
            { onPress = Just TogglePivotReshaper
            , label = text "Pivot Reshaper"
            }
        ]
buttonTogglePivotReshaper : Model -> Int -> Element Msg
buttonTogglePivotReshaper model size =
    let
        tooltipText =
            if model.showPivotReshaper then
                "Hide Pivot Reshaper"

            else
                "Show Pivot Reshaper"
    in
    Theme.button 
        [ width shrink 
        , alignTop
        , alignLeft
        , Border.rounded 10
        , padding 2 
        , tooltip above (lightTooltip tooltipText)
        ]
            { onPress = Just TogglePivotReshaper
            , label = 
                image 
                    [ width (px size), height (px size) ] 
                    {src = 
                        if model.showPivotReshaper then
                            "/assets/pivotPressed.png"
                        else
                            "/assets/pivot.png"

                    , description = "Pivot Reshaper"}
            }

buttonToggleFormulaEditor : Model -> Int -> Element Msg
buttonToggleFormulaEditor model size =
    let
        tooltipText =
            if model.showFormulaEditor then
                "Hide Formula Editor"

            else
                "Show Formula Editor"
    in
    Theme.button 
        [ width shrink 
        , alignTop
        , alignLeft
        , Border.rounded 10
        , padding 2
        , tooltip above (lightTooltip tooltipText)
        ]
            { onPress = Just ToggleFormulaEditor
            , label = 
                image 
                    [ width (px size), height (px size) ] 
                    {src = 
                        if model.showFormulaEditor then
                            "/assets/formulaEditor.png"
                        else
                            "/assets/formulaEditor.png"

                    , description = "Formula editor"}
            }

buttonRecalculate : Model -> Int -> Element Msg
buttonRecalculate model size =
    let
        tooltipText =
            "Recalculate"
    in
    Theme.button 
        [ width shrink 
        , alignTop
        , alignLeft
        , Border.rounded 10
        , padding 2 
        , tooltip above (lightTooltip tooltipText)
        ]
            { onPress = Just (CalcMsg EvalFormulas) 
            , label = 
                image 
                    [ width (px size), height (px size) ] 
                    {src = 
                            "/assets/recalculate.png"


                    , description = tooltipText
                    }
            }

buttonUpdateFormulas : Model -> Int -> Element Msg
buttonUpdateFormulas model size =
    let
        tooltipText =
            "Update formulas and recalculate"
    in
    Theme.button 
        [ width shrink 
        , alignTop
        , alignLeft
        , Border.rounded 10
        , padding 2 
        , tooltip above (lightTooltip tooltipText)
        ]
            { onPress = Just (CalcMsg UpdateFormulas)
            , label = 
                image 
                    [ width (px size), height (px size) ] 
                    {src = "/assets/recalculate.png"
                            --"/assets/updateFormulas.png"


                    , description = "Update Formulas"}
            }

viewLogs : Model -> Element Msg
viewLogs model =
    if model.showLogs then
        Element.map CalcMsg <| CalcEngine.viewConsole model.calcModel

    else
        Element.none


logo : Element Msg
logo =
    el [ height (px 60), width (px 250), alignLeft ]
        (Element.image [] { src = "/assets/logo.png", description = "elmFoldbook Logo" })


stickyTopHeaderAttrs : List (Attribute msg)
stickyTopHeaderAttrs =
    [ Element.htmlAttribute (style "position" "sticky")
    , Element.htmlAttribute (style "top" "0px")
    , Element.htmlAttribute (style "z-index" "3")
    ]


stickyLeftHeaderAttrs : List (Attribute msg)
stickyLeftHeaderAttrs =
    [ Element.htmlAttribute (style "position" "sticky")
    , Element.htmlAttribute (style "left" "0px")
    , Element.htmlAttribute (style "z-index" "3")
    ]


viewTitle : String -> Element Msg
viewTitle titleText =
    el
        ([ UiFont.size 40
         , UiFont.family [ UiFont.typeface "Raleway", UiFont.sansSerif ]
         , paddingEach { top = 12, bottom = 8, left = 0, right = 0 }

         --, alignLeft
         , centerY
         , height fill
         , width fill --(px 600)
         , Background.color MyColors.white
         ]
            ++ stickyLeftHeaderAttrs
        )
    <|
        text titleText



-- presa da Korban p. 121


htmlAttributes : List (Html.Attribute Msg) -> List (Attribute Msg)
htmlAttributes =
    List.map htmlAttribute



-- init : Result Error Env -> DatasetRef -> (Model, Result Error Env, Cmd Msg)
-- init env datasetRef =
--     let
--         model = initialModel env datasetRef
--         initialFocusCmd = Cmd.none -- Cmd.map SpreadsheetUIMsg SpreadsheetUI.focusA1
--         curCalcModel = model.calcModel
--         initializeEditorCmd = Ports.initializeEditor { editorId = editorId, initialValue = curCalcModel.input }
--         initEditorUpdateMsg = AppUtil.cmdMsg (InitializeEditor )
--     in
--     ( { model | editorInitialized = False }
--     , env
--     , Cmd.batch [initialFocusCmd, initializeEditorCmd, initEditorUpdateMsg]
--     )


init : Result Error Env -> DatasetRef -> ( Model, Result Error Env, Cmd Msg )
init env datasetRef =
    let
        model =
            initialModel env datasetRef

        -- editorId = model.editorId
        -- initialFocusCmd = Cmd.none -- Cmd.map SpreadsheetUIMsg SpreadsheetUI.focusA1
        -- payload = { editorId = editorId, initialValue = model.calcModel.input }
        -- initializeEditorCmd = Ports.initializeEditor payload
        -- initEditorUpdateMsg = cmdMsg InitEditor -- cmdMsg InitEditorWithId
    in
    -- Debug.log ("init model payload" ++ Debug.toString payload) -- ok is executed
    ( model
    , env
      --, Cmd.batch [initialFocusCmd, initializeEditorCmd, initEditorUpdateMsg])
      --, Cmd.none) -- initializeEditorCmd is executed in the view
    , Cmd.map CalcMsg (cmdMsg CalcEngine.EvalFormulas)
    )



-- trigger recalculation


subscriptions : Model -> Sub Msg
subscriptions model =
    Sub.batch
        [ Sub.map SpreadsheetUIMsg (SpreadsheetUI.subscriptions model.spreadsheetUIModel)
        , Ports.formulaContentChanged FormulaContentChanged
        , Ports.requestHints RequestHints
        ]



-- main : Program () Model Msg
-- main =
--     Browser.element
--         { init = init
--         , update = update
--         , view = view
--         , subscriptions = subscriptions
--         }
