module DatasetPage exposing (..) -- former single page Main.elm
-- TO BUILD
-- remove /build folder
-- > make all
-- TO RUN
-- > elm-watch hot
-- NB: to change the executed js comment/uncomment in the index.html
-- ./dist/ui.js is generated by Makefile, from console: make all (after deleting /build folder)
-- app.js is generated by elm make src/Main.elm --output=app.js
-- elm-watch hot works with both (I assume it goes after index.html in the running folder)
import Platform.Cmd as Cmd
import Platform.Sub as Sub
-- spreadsheetUI and pivot tables
-- import PersonValuePivot exposing (..)
import SpreadsheetUI exposing (..)

-- Drag and drop
import DnDTray exposing (..)
-- Dropdown
import Dropdown exposing (Msg(..))

-- XModel and CalcEngine
import CalcEngine exposing (Msg(..))
import TypesXModel exposing (XModel )
import XModel 
import TypesXModel exposing (..)
import XView
import Types exposing (CallTree(..), Error(..), Value(..), Env)

-- elm-interpreter
import Ports

-- UI

import Html 
import Html.Attributes as HtmlAttr exposing (style)
import Html.Events 
import Element exposing (..)
import Element.Font as UiFont
import Element.Background as Background
import Element.Border as Border
import MyColors exposing (..)
import Browser.Navigation as Navigation
import Element.Input as Input
import UI.Theme as Theme

import Array
import Array2D
import Html 
import FastDict as Dict exposing (Dict)
import Json.Decode as Decode
import AppUtil exposing (cmdMsg)
import Time exposing (now)





type alias Model =
    { spreadsheetUIModel : SpreadsheetUI.Model
    , dndTrayModel : DnDTray.Model
    , calcModel : CalcEngine.Model
    , autoRecalc : Bool 
    , hints : List String 
    , editorId : String
    , showFormulaEditor : Bool
    , showPivotReshaper : Bool
    , showLogs : Bool
    }

initialModel : Result Error Env -> DatasetRef  -> Model
initialModel env datasetRef  =
    let
        initialShowFormulaEditor = True
        initialShowPivotReshaper = True
        initialShowLogs = True
        initialCalcModel = CalcEngine.initialModel env datasetRef
        initialXModel = CalcEngine.getXModelFromEnv env |> Maybe.withDefault XModel.emptyXModel
        initialSpreadsheetUIModel = SpreadsheetUI.initialModel initialXModel datasetRef
        initialDnDTrayModel = DnDTray.initialModel
        initialTrayData = XView.defaultTrayData initialXModel.dims
                initialSpreadsheetUIModel.curDataset initialSpreadsheetUIModel.curDatasetView
        initialEditorId = "editor-" ++ datasetRef
    in
    { spreadsheetUIModel = initialSpreadsheetUIModel
    , dndTrayModel = { initialDnDTrayModel | trayData = initialTrayData }
    , calcModel = initialCalcModel
    , autoRecalc = False
    , hints = []
    , editorId = initialEditorId
    , showFormulaEditor = initialShowFormulaEditor
    , showPivotReshaper = initialShowPivotReshaper
    , showLogs = initialShowLogs
    }


type Msg 
    = DnDTrayMsg DnDTray.Msg
    | SpreadsheetUIMsg SpreadsheetUI.Msg
    | CalcMsg CalcEngine.Msg -- formerly UI.Msg
    -- | Initialize
    | ReceiveHints {editorId : String, hints :  List String}  -- Include editorId
    | FormulaContentChanged String
    | RequestHints { editorId : String, word : String }
    | InitEditor
    | OpenDataset Navigation.Key String
    | TriggerPageReload
    | ToggleFormulaEditor
    | TogglePivotReshaper



type alias  Models = { calc : CalcEngine.Model, x : XModel, ui : SpreadsheetUI.Model }

-- Update-
-- no need to add xModel to update args in Main, it is already in model here
-- in component must add xModel to update in order to send/receive xModel to/from Main

update : Msg -> Result Error Env -> Model -> (Model, Result Error Env , Cmd Msg)
update msg prevEnv model =
    case msg of
        SpreadsheetUIMsg subMsg ->
            let
                curCalcModel = model.calcModel
                curEnv = prevEnv
                curXModel = getCurXModelFromEnv curEnv

                -- Update the spreadsheetUIModel and xModel from the subMsg action in SpreadsheetUI
                (sUiModel1, xModel1, sUiCmd1) = SpreadsheetUI.update subMsg model.spreadsheetUIModel curXModel

                -- Function to handle recalculation if needed
                --  RECALC TRIGGERING MOVED TO MAIN EnvUpdated but still needed here, TODO: check if needed
                handleRecalc : List DatasetRef -> CalcEngine.Model -> XModel -> SpreadsheetUI.Model -> (Models, List (Cmd Msg))
                handleRecalc datasetRefs calcModel xModel sUiModel =
                    case List.filter (\r-> r == calcModel.datasetRef) datasetRefs |> List.head  of
                        Just datasetName -> -- calcModel.datasetRef is in datasetsToRecalc
                                let
                                    -- SaveCell populates datasetsToRecalc
                                    envWithChangedXModel = CalcEngine.setXModelToEnv curEnv xModel
                                    -- trigger recalculation, disabled, moved to EnvUpdated
                                    (calcModelCalculated, envCalculated, calcCmd) = CalcEngine.update CalcEngine.EvalFormulas calcModel envWithChangedXModel
                                    xModelCalculated = CalcEngine.getXModelFromEnv envCalculated |> Maybe.withDefault XModel.emptyXModel
                                -- Step 2: Update SpreadsheetUI with updated XModel
                                    (sUiModelRefresh, xModelRefresh, sUiCmdRefresh) = 
                                        SpreadsheetUI.update 
                                            SpreadsheetUI.RefreshFromXModel 
                                                sUiModel 
                                                xModelCalculated 
                                    curCalcCmds = [Cmd.map CalcMsg calcCmd, Cmd.map SpreadsheetUIMsg sUiCmdRefresh]
                                    curModels = {calc=calcModelCalculated, x=xModelRefresh, ui=sUiModelRefresh}
                                in
                                (curModels, curCalcCmds)

                        Nothing ->
                            -- No recalculation needed, return the same models and no command
                            ({calc=calcModel, x=xModel, ui=sUiModel}, [Cmd.none])
                -- end of handleRecalc



                (models, recalcCmds) =  
                    handleRecalc xModel1.datasetsToRecalc curCalcModel xModel1 sUiModel1
                    --({calc=curCalcModel, x=xModel1, ui=sUiModel1}, [Cmd.none])  -- no recalc
                finalModel =
                    { model 
                        | spreadsheetUIModel = sUiModel1 -- models.ui
                        , calcModel = models.calc
                    }
                finalEnv = CalcEngine.setXModelToEnv curEnv models.x

                finalCmds =
                    [ Cmd.map SpreadsheetUIMsg sUiCmd1 ] ++ recalcCmds
            in

            (finalModel, finalEnv, Cmd.batch finalCmds)
  
        DnDTrayMsg subMsg ->
            case subMsg of
                DnDTray.DnDTrayDropdownMsg dropdownId dropdownMsg ->
                    let
                        -- Forward the dropdown message to DnDTray.update and handle the response
                        (updatedDndGroups, cmd) = DnDTray.update (DnDTray.DnDTrayDropdownMsg dropdownId dropdownMsg) model.dndTrayModel
                    in
                    ({ model | dndTrayModel = updatedDndGroups }
                    , prevEnv
                    , Cmd.map DnDTrayMsg cmd)

                DnDTray.DnDTrayOptionPicked dropdownId option ->
                    -- Handle option picked and update the dataset view
                    -- pivot update copied from DnDTray.DnDMsg 
                    let
                        (updatedDndGroups, cmd) = DnDTray.update subMsg model.dndTrayModel
                        -- updates for new dropdoen selection
                        updatedDataview = XView.updateDropdownOption dropdownId (Maybe.withDefault "" option) model.spreadsheetUIModel.curDatasetView
                        curSpreadsheetModel = model.spreadsheetUIModel
                        -- first round of update to set thetrays and  new datasetView 
                        updatedSpreadsheetUIModel = 
                            { curSpreadsheetModel 
                                | curDatasetView = updatedDataview
                            }
                        updatedModel = { model 
                            | spreadsheetUIModel = updatedSpreadsheetUIModel
                            -- needed to keep dropdown selection
                            , dndTrayModel = updatedDndGroups
                            }

                        -- removed this passage that initializes pageTray coords to first
                        --  updatedSpreadsheetUIModel = updateDatasetViewFromTrays updatedModel -- check pageTray overwrite
                        -- refresh spreadsheet data and index
                        curXModel = prevEnv |> CalcEngine.getXModelFromEnv |> Maybe.withDefault XModel.emptyXModel
                        (newSpreadsheet, newIndex) = 
                            SpreadsheetUI.getCurrentSpreadsheetAndIndexFromView updatedSpreadsheetUIModel curXModel
                        -- updates cellsUI with new spreadsheet
                        updatedCellsUI = SpreadsheetUI.updateCellsUI updatedSpreadsheetUIModel.cellsUI newSpreadsheet
                        updatedSpreadsheetUIModelBis = 
                            { updatedSpreadsheetUIModel | spreadsheet = newSpreadsheet, spreadsheetIndex = newIndex
                            -- aggiorna lo spreadsheet unica colonna non cambia colHeaders
                            , cellsUI =  updatedCellsUI
                            }

                    in
                    -- Debug.log ("(dropdownId, option)" ++ Debug.toString (dropdownId, option))
                    -- Debug.log ("updatedDataview" ++ Debug.toString updatedDataview.pageTray)
                    ({ updatedModel   
                        | spreadsheetUIModel = updatedSpreadsheetUIModelBis 
                        --, dndTrayModel = updatedDndGroups
                    }
                    -- cmd restituito da DnDTray.update chiamato sopra
                    , prevEnv
                    , Cmd.map DnDTrayMsg cmd) 

                DnDTray.DnDMsg _ ->
                    -- Handle other DnDTray messages as before
                    let
                        -- passa l'update event al model di DnDTray e riceve il cmd da eseguire
                        -- lo stesso cmd viene eseguito alla fine
                        -- qui subito aggiorna le info per camnbiare i Tray
                        (updatedDndGroups, cmd) = DnDTray.update subMsg model.dndTrayModel
                        -- con i Tray cambiati parte il reshape della pivot table
                        updatedModel = { model | dndTrayModel = updatedDndGroups }
                        -- se uso updatedSpreadsheetUIModel funziona
                        updatedSpreadsheetUIModel = updateDatasetViewFromTrays updatedModel prevEnv

                        --(newSpreadsheet, newIndex) = SpreadsheetUI.getCurrentSpreadsheetAndIndexFromTable updatedSpreadsheetUIModel
                        curXModel = prevEnv |> CalcEngine.getXModelFromEnv |> Maybe.withDefault XModel.emptyXModel
                        (newSpreadsheet, newIndex) = 
                            SpreadsheetUI.getCurrentSpreadsheetAndIndexFromView updatedSpreadsheetUIModel curXModel

                        updatedSpreadsheetUIModelBis = 
                            let
                                nrCols = Array2D.columns newSpreadsheet
                                nrRows = Array2D.rows newSpreadsheet
                            in 
                            { updatedSpreadsheetUIModel | spreadsheet = newSpreadsheet, spreadsheetIndex = newIndex
                            -- aggiorna lo spreadsheet unica colonna non cambia colHeaders
                            , cellsUI = (SpreadsheetUI.updateCellsUI updatedSpreadsheetUIModel.cellsUI newSpreadsheet)
                            , nrCols = nrCols
                            , nrRows = nrRows
                            , columnWidths = Array.repeat nrCols updatedSpreadsheetUIModel.defaultColumnWidth
                            }
                    in
                    -- Debug.log ("DnDMsg handled" ++ Debug.toString subMsg)
                    ({ updatedModel   | spreadsheetUIModel = updatedSpreadsheetUIModelBis 
                    }
                    -- cmd restituito da DnDTray.update chiamato sopra
                    , prevEnv
                    , Cmd.map DnDTrayMsg cmd) -- con Cmd.none non funziona il drag and drop

        CalcMsg calcMsg ->
            let
                (updatedCalcModel, newEnv, calcCmd) = CalcEngine.update calcMsg model.calcModel prevEnv
                curDatasetName = model.spreadsheetUIModel.curDataset.ref
                updatedXModel = CalcEngine.getXModelFromEnv newEnv |> Maybe.withDefault XModel.emptyXModel
                curDataset = XModel.getDatasetByRef curDatasetName updatedXModel.datasets |> Maybe.withDefault XModel.emptyDataset
                updatedSpreadsheetUIModel = SpreadsheetUI.updateSpreadsheetFromXModel model.spreadsheetUIModel updatedXModel curDataset
            in
            -- Debug.log ("updatedDataset.data" ++ Debug.toString curDataset)
            (-- add updateSpreadsheetUIModel
                { model 
                | spreadsheetUIModel = updatedSpreadsheetUIModel
                , calcModel = updatedCalcModel 
             }
             , newEnv
             , Cmd.map CalcMsg calcCmd)

        FormulaContentChanged content ->
            let
                prevCalcModel = model.calcModel
                updatedCalcModel = { prevCalcModel | formulaInput = content }
            in
            ( { model | calcModel = updatedCalcModel }
              , prevEnv
              , Cmd.none )
        RequestHints { editorId , word  } ->
            let
                curXModel = getCurXModelFromEnv prevEnv
                hints = getHints curXModel model.calcModel.datasetRef word
                editorIdElm = model.editorId
            in
            if editorId == editorIdElm then
                (model, prevEnv, sendHintsToJs editorId hints)
            else
                (model, prevEnv
                -- , sendHintsToJs editorIdElm ["mismatched editorIds: js=" ++ editorId ++ " and elm=" ++ editorIdElm]
                , Cmd.none
                )

        ReceiveHints { editorId, hints } ->
            if editorId == model.editorId then
                ({ model | hints = hints }, prevEnv, Cmd.none)
            else
                (model, prevEnv, Cmd.none)
        
        InitEditor -> -- editor init moved to init as direct port call
            ( model, prevEnv, Cmd.none )
        OpenDataset key datasetName ->
            (model, prevEnv
            , Cmd.batch [navigateToDataset key datasetName, cmdMsg TriggerPageReload] 
            )
        TriggerPageReload ->
            --( model, prevEnv, Ports.reloadPage () )
            ( model, prevEnv, Cmd.none )
        ToggleFormulaEditor ->
            ( { model | showFormulaEditor = not model.showFormulaEditor }, prevEnv, Cmd.none )
        TogglePivotReshaper ->
            ( { model | showPivotReshaper = not model.showPivotReshaper }, prevEnv, Cmd.none )



sendHintsToJs : String -> List { label : String} -> Cmd Msg
sendHintsToJs editorId hints =
    let payload = { editorId = editorId, hints = hints } in
    -- Debug.log ("sendHintsToJs payload" ++ Debug.toString payload)
    Ports.receiveHints payload

getHints : XModel -> DatasetRef -> String -> List { label : String }
getHints xModel datasetRef word =
    XModel.promptCoordsForPartialRangeName xModel datasetRef word


getCurXModelFromEnv : Result Error Env -> XModel
getCurXModelFromEnv env  = env |> CalcEngine.getXModelFromEnv |> Maybe.withDefault XModel.emptyXModel
-- add coords like in expression parsing!!!


-- used in DnDTrayMsg subMsg, returns updated SpreadsheetUI.Model set to model.spreadsheetUIModel
-- then continues with update cellsUI from spreadsheetUI
-- rationalize to avoid duplication of steps in update or use of stale model data modified by update
updateDatasetViewFromTrays : Model -> Result Error Env -> SpreadsheetUI.Model
updateDatasetViewFromTrays model curEnv =
    let
        -- common step get from trays the names of the pages, rows and columns
        -- to trigger when tokens are moved across trays
        pageNames = DnDTray.getPageNames model.dndTrayModel.trayData
        rowNames = DnDTray.getRowNames model.dndTrayModel.trayData
        colNames = DnDTray.getColNames model.dndTrayModel.trayData

        -- set shapes and data as required by XArray and update model.datasetView
        curXModel = curEnv |> CalcEngine.getXModelFromEnv |> Maybe.withDefault XModel.emptyXModel
        updatedDataview = XView.updateDatasetViewTrays 
            curXModel.dims
            model.spreadsheetUIModel.curDataset
            model.spreadsheetUIModel.curDatasetView 
            pageNames rowNames colNames 
      
        -- gets current spreadsheetUI model
        curSpreadsheetModel = model.spreadsheetUIModel
    in
    -- returns updated spreadsheetUI model with shape settings for MyPivotTable and datasetView with shape and data
    { curSpreadsheetModel 
        | curDatasetView = updatedDataview
    }


-- View

-- Helper function to generate the navigation menu
viewNavMenu : List String -> Element Msg
viewNavMenu datasetNames =
    row [ spacing 10, padding 10 ]
        (List.map (\name -> 
            link 
                [ UiFont.color blue,  UiFont.family [(UiFont.typeface "Raleway"), UiFont.sansSerif] ]
                { url = "/#/dataset/" ++ name
                , label = text name
                }
        ) datasetNames)
-- alternative to navMenu
-- Helper function to generate the navigation tabs
viewDatasetNavTabs : Navigation.Key -> List String -> String -> Element Msg
viewDatasetNavTabs  key datasetNames currentDataset =
    row [ spacing 10, padding 10 ]
        (List.map (\name -> 
            let
                isSelected = name == currentDataset
                tabStyle = 
                    [ UiFont.family [(UiFont.typeface "Raleway"), UiFont.sansSerif]
                    , UiFont.color (if isSelected then darkCharcoal else darkGray)
                    , paddingEach {top=8, right=16, bottom= 8,left = 16}
                    , Border.color (if isSelected then darkGray else lightGray)
                    , Background.color (if isSelected then lightGray else white)
                    , (if isSelected then UiFont.bold else UiFont.light)
                    , Border.rounded 4
                    , Border.solid
                    , Border.width (if isSelected then 2 else 1)
                    , if isSelected then UiFont.bold else UiFont.regular
                    ]
            in
            Element.el tabStyle
                (Input.button [  ]
                    { onPress = Just (OpenDataset key name), label = text name } )

        ) datasetNames)

navigateToDataset : Navigation.Key -> String -> Cmd Msg
navigateToDataset key datasetName =
    let
        url = "/#/dataset/" ++ datasetName
    in
    Navigation.pushUrl key url

-- shows dataset nav toolbar, trays, spreadsheet, formula editor, logs
view : Navigation.Key -> Result Error Env -> Model -> Element Msg
view key curEnv model  =
    let
        modalView = Element.map SpreadsheetUIMsg <| SpreadsheetUI.spreadsheetModalView model.spreadsheetUIModel
        lenSpreadsheetWidth = 1200 -- 600px
        curXModel = curEnv |> CalcEngine.getXModelFromEnv |> Maybe.withDefault XModel.emptyXModel
        pivotTableView = SpreadsheetUI.viewPivotTableFromSpreadsheetView model.spreadsheetUIModel curXModel
        datasetNames = curXModel.datasetRefs

    in 
    column [ inFront modalView ] -- messi 600px larghezza sheet si adatta se superiore no se inferiore
        [ 
        -- title and dim trays
        column [] -- styles of trays set in DnDTray group styles
        [ row [width fill, spacing 6] [logo, viewTitle curXModel.modelRef]
        , viewDatasetNavTabs key datasetNames model.spreadsheetUIModel.curDataset.ref
        --, (viewNavMenu datasetNames)
        ]
        -- spreadsheet in pivot table
        , row [ width (px lenSpreadsheetWidth), height shrink ]
          [ Element.map SpreadsheetUIMsg pivotTableView  ]
        , column [ width (px lenSpreadsheetWidth), height shrink ]
             [ row [spacing 10] 
                [Element.map CalcMsg <| CalcEngine.viewCommands 
                , buttonToggleFormulaEditor
                ]
             , viewPivotReshaper model lenSpreadsheetWidth
             , viewFormulaEditor model
             -- logging calculation messages, activated via mode.showLogs in Main.init
             , viewLogs model
             ]
        ]
-- without logo and title
viewSheet : Result Error Env -> Model -> Element Msg
viewSheet curEnv model  =
    let
        modalView = Element.map SpreadsheetUIMsg <| SpreadsheetUI.spreadsheetModalView model.spreadsheetUIModel
        lenSpreadsheetWidth = 1200 -- 600px
        curXModel = curEnv |> CalcEngine.getXModelFromEnv |> Maybe.withDefault XModel.emptyXModel
        pivotTableView = SpreadsheetUI.viewPivotTableFromSpreadsheetView model.spreadsheetUIModel curXModel

    in 
    column [ inFront modalView ] -- messi 600px larghezza sheet si adatta se superiore no se inferiore
        [ 
        -- title and dim trays
        column [width fill] -- styles of trays set in DnDTray group styles
        -- spreadsheet in pivot table
            [ row [ width (px lenSpreadsheetWidth), height shrink ]
            [ Element.map SpreadsheetUIMsg pivotTableView  ]
            , column [ width (px lenSpreadsheetWidth), height shrink ]
                [ row [spacing 10, width fill] 
                    [Element.map CalcMsg <| CalcEngine.viewCommands 
                    , buttonToggleFormulaEditor
                    ]
                , viewPivotReshaper model lenSpreadsheetWidth
                , viewFormulaEditor model
                -- logging calculation messages, activated via mode.showLogs in Main.init
                , viewLogs model
                ]
            ]
        ]

viewPivotReshaper : Model -> Int -> Element Msg
viewPivotReshaper model lenSpreadsheetWidth =
    if model.showPivotReshaper then
        column [ UiFont.size 14, width (px lenSpreadsheetWidth) ] -- cannot set dynamically to max width of container elements
                [ Element.map DnDTrayMsg <| DnDTray.pageTrayView model.dndTrayModel
                    -- brought row tray and column tray together for easier reshaping
                , row [ width fill, height (px 120) ] -- no shrink loses row headers
                    -- in DnDTray all trays are set to width fill
                        [ Element.map DnDTrayMsg <| DnDTray.rowTrayView model.dndTrayModel
                        , Element.map DnDTrayMsg <| DnDTray.columnTrayView model.dndTrayModel
                        , Element.map DnDTrayMsg <| DnDTray.ghostView model.dndTrayModel.dnd model.dndTrayModel.trayData
                        ]
                    ]
    else
        Element.none

viewFormulaEditor : Model -> Element Msg
viewFormulaEditor model =
    let
        editorElement editorId input =
            -- aborted attempt to generate editorId with a Task, here was pased -- model.editorId of
            case editorId of 
                Just editorIdJust ->
                    Element.html <| Html.node "code-mirror-formula-editor"
                        [ HtmlAttr.attribute "data-initial-value" input
                        , HtmlAttr.attribute "id" editorIdJust
                        , Html.Events.on "formulaContentChanged" (Decode.map FormulaContentChanged (Decode.at [ "detail" ] Decode.string)) 
                        ] []
                Nothing ->
                    Element.none
    in
    if model.showFormulaEditor then
        column [ padding 20, spacing 10, width fill ]
            [ row ([ UiFont.size 24, UiFont.bold, width fill] ++ noWrapAttributes) [ text "Formula Editor" ]
            , el [ UiFont.size 16, width fill] (editorElement  (Just model.editorId) model.calcModel.formulaInput)
            ]
    else
        Element.none

noWrapAttributes : List (Attribute msg)
noWrapAttributes =
    [ Element.htmlAttribute (style "white-space" "nowrap")
    -- , Element.htmlAttribute (style "overflow" "hidden")
    -- , Element.htmlAttribute (style "text-overflow" "ellipsis")
    ]
buttonToggleFormulaEditor : Element Msg
buttonToggleFormulaEditor =
    Theme.boxRow "Show/Hide" ([width <| fillPortion 1, alignTop] )
        [(Theme.button [width shrink]
            { onPress = Just ToggleFormulaEditor
            , label = text "Formula Editor" } )
        , (Theme.button [width shrink]
            { onPress = Just TogglePivotReshaper
            , label = text "Pivot Reshaper" } )
        ]

viewLogs : Model -> Element Msg
viewLogs model =
    if model.showLogs then
            Element.map CalcMsg <| CalcEngine.viewConsole model.calcModel 
    else
        Element.none

logo : Element Msg
logo =
    el [ height (px 60), width (px 250), alignLeft ]
        (Element.image [  ] { src = "/assets/logo.png", description = "elmFoldbook Logo" })     


stickyTopHeaderAttrs : List (Attribute msg)
stickyTopHeaderAttrs =
    [ Element.htmlAttribute (style "position" "sticky")
    , Element.htmlAttribute (style "top" "0px")
    , Element.htmlAttribute (style "z-index" "3")
    ]
stickyLeftHeaderAttrs : List (Attribute msg)
stickyLeftHeaderAttrs =
    [ Element.htmlAttribute (style "position" "sticky")
    , Element.htmlAttribute (style "left" "0px") 
    , Element.htmlAttribute (style "z-index" "3")
    ]
viewTitle : String -> Element Msg
viewTitle titleText =
    el ([ UiFont.size 40
        , UiFont.family [(UiFont.typeface "Raleway"), UiFont.sansSerif]
        , paddingEach {top=12, bottom=8, left=0, right=0}
        --, alignLeft
        , centerY
        , height fill
        , width fill --(px 600)
        , Background.color MyColors.white
        ] ++ stickyLeftHeaderAttrs)
        <| text titleText


-- presa da Korban p. 121
htmlAttributes : List (Html.Attribute Msg) -> List (Attribute Msg) 
htmlAttributes =
    List.map htmlAttribute


-- init : Result Error Env -> DatasetRef -> (Model, Result Error Env, Cmd Msg)
-- init env datasetRef =
--     let
--         model = initialModel env datasetRef
--         initialFocusCmd = Cmd.none -- Cmd.map SpreadsheetUIMsg SpreadsheetUI.focusA1
--         curCalcModel = model.calcModel
--         initializeEditorCmd = Ports.initializeEditor { editorId = editorId, initialValue = curCalcModel.input }
--         initEditorUpdateMsg = AppUtil.cmdMsg (InitializeEditor )
--     in
--     ( { model | editorInitialized = False }
--     , env
--     , Cmd.batch [initialFocusCmd, initializeEditorCmd, initEditorUpdateMsg]
--     )
init : Result Error Env -> DatasetRef -> (Model, Result Error Env, Cmd Msg)
init env datasetRef =
    let
        model = initialModel env datasetRef
        -- editorId = model.editorId
        -- initialFocusCmd = Cmd.none -- Cmd.map SpreadsheetUIMsg SpreadsheetUI.focusA1
        -- payload = { editorId = editorId, initialValue = model.calcModel.input }
        -- initializeEditorCmd = Ports.initializeEditor payload
        -- initEditorUpdateMsg = cmdMsg InitEditor -- cmdMsg InitEditorWithId
    in
    -- Debug.log ("init model payload" ++ Debug.toString payload) -- ok is executed
    (model
    , env
    --, Cmd.batch [initialFocusCmd, initializeEditorCmd, initEditorUpdateMsg])
    --, Cmd.none) -- initializeEditorCmd is executed in the view
    , Cmd.map CalcMsg (cmdMsg CalcEngine.EvalFormulas)) -- trigger recalculation





subscriptions : Model -> Sub Msg
subscriptions model =
    Sub.batch
        [ Sub.map DnDTrayMsg (DnDTray.subscriptions model.dndTrayModel)
        , Sub.map SpreadsheetUIMsg (SpreadsheetUI.subscriptions model.spreadsheetUIModel)
        , Ports.formulaContentChanged FormulaContentChanged
        , Ports.requestHints RequestHints
        ]


-- main : Program () Model Msg
-- main =
--     Browser.element
--         { init = init
--         , update = update
--         , view = view
--         , subscriptions = subscriptions
--         }



